## Numpy : Package for Multi-Dimensional Array

In [2]:
import numpy as np 
#insted of np we can write anything

In [3]:
arr=np.array([1,2,3,4,5,6])
#np.array is used to create array and list is used as data structure

In [22]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_list)

In [5]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
tup=((1,2,3,4),(1,2,3,4))
tup

((1, 2, 3, 4), (1, 2, 3, 4))

In [27]:
samp=np.array(tup)
samp

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [9]:
np.arange(15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(1,50,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [14]:
np.zeros(10)
#Default type Float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones((9,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
### Create an array of zeros with 2 row and 10 column

In [34]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
np.linspace(0,29,6)

array([ 0. ,  5.8, 11.6, 17.4, 23.2, 29. ])

In [36]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [37]:
np.random.rand(3,4)

array([[0.65748531, 0.32259111, 0.54545678, 0.59979969],
       [0.60455938, 0.16556552, 0.16368167, 0.27261762],
       [0.96937427, 0.054358  , 0.41571176, 0.35129369]])

In [38]:
np.random.randn(3,5)

array([[ 0.80149552,  1.14691056, -0.1956159 ,  0.55552743,  0.37264555],
       [-0.56224026, -0.82701236,  0.2965186 ,  0.16355144, -1.47790513],
       [-1.62471818, -1.0085884 ,  0.92793591, -0.67715341,  2.13488243]])

In [39]:
np.random.randint(1,4)

2

In [40]:
np.random.randint(33,55,22)

array([33, 51, 33, 35, 47, 40, 41, 39, 34, 47, 38, 41, 44, 33, 40, 50, 40,
       50, 53, 43, 39, 40])

In [50]:
sample_array=np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
rand_array=np.random.randint(0,444,30)

In [46]:
rand_array

array([431, 248, 126, 295, 219, 213, 295, 190, 236, 293, 106, 425,  16,
        92,  88, 169,   4,  69, 423, 240, 290, 187, 391,  22, 421, 245,
       114, 301,  47, 105])

In [51]:
sample_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [53]:
np.linspace(0,20,9)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.random.rand(4,3)

array([[0.39134361, 0.33755452, 0.02492202],
       [0.32904119, 0.67333907, 0.6313661 ],
       [0.59604477, 0.01252216, 0.54515028],
       [0.78324967, 0.20469863, 0.7650234 ]])

In [56]:
np.random.randn(3,4)

array([[ 0.51358393, -0.01346461,  0.78931661,  0.00530577],
       [ 1.60813656, -0.16306007, -0.25530892,  0.85404153],
       [-0.46792577, -0.01867302,  0.30514125,  0.95962863]])

In [57]:
sample_array=np.arange(30)

In [58]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [69]:
rand_array

array([431, 248, 126, 295, 219, 213, 295, 190, 236, 293, 106, 425,  16,
        92,  88, 169,   4,  69, 423, 240, 290, 187, 391,  22, 421, 245,
       114, 301,  47, 105])

In [59]:
rand_array.min()

4

In [60]:
rand_array.argmin()

16

In [70]:
rand_array.argmax()

0

In [61]:
a=np.eye(4)

In [62]:
a.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
s=np.random.rand(2,4)

In [64]:
s.T

array([[0.53734662, 0.72321521],
       [0.00358656, 0.924512  ],
       [0.03709061, 0.8150895 ],
       [0.46402409, 0.15897109]])

In [72]:
sample_array=np.arange(10,21)

In [73]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [74]:
sample_array[4]

14

In [75]:
sample_array[3:7]

array([13, 14, 15, 16])

In [76]:
sample_array[1:4]=100

In [77]:
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [79]:
sample_array[0:7]
#slicing of array taking part of it

array([ 10, 100, 100, 100,  14,  15,  16])

In [80]:
subset_array=sample_array[0:7]

In [81]:
subset_array

array([ 10, 100, 100, 100,  14,  15,  16])

## 2D Array

In [ ]:
#Matrix
#2D arrray

In [95]:
sample_matrix=np.random.rand(3,4)


In [96]:
sample_matrix

array([[0.01404787, 0.88811696, 0.10450365, 0.90523986],
       [0.42644289, 0.80683684, 0.91237684, 0.5554649 ],
       [0.15546789, 0.61594126, 0.00617783, 0.15999274]])

In [97]:
sample_matrix[0:2,2]

array([0.10450365, 0.91237684])

In [98]:
sample_matrix[2,:]

array([0.15546789, 0.61594126, 0.00617783, 0.15999274])

In [99]:
sample_matrix[2]

array([0.15546789, 0.61594126, 0.00617783, 0.15999274])

In [100]:
sample_matrix[:,(3)]

array([0.90523986, 0.5554649 , 0.15999274])

In [101]:
sample_matrix[:,(3,2)]

array([[0.90523986, 0.10450365],
       [0.5554649 , 0.91237684],
       [0.15999274, 0.00617783]])

In [106]:
sample_array=np.arange(1,20)

In [107]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [108]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [110]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [112]:
np.std(sample_array)

5.477225575051661

In [113]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [114]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [115]:
np.max(sample_array)

19

In [116]:
np.min(sample_array)

1

In [118]:
np.argmax(sample_array)

18

In [119]:
np.argmin(sample_array)

0

In [120]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [123]:
np.var(sample_array)

30.0

In [124]:
np.mean(sample_array)

10.0

In [129]:
np.median(sample_array)

10.0

In [125]:
array=np.random.randn(3,5)

In [126]:
array

array([[-1.91947604, -0.29616999,  0.63430221,  0.1182812 ,  1.72776044],
       [-2.81170383,  0.40574449, -1.38194438, -1.32629677, -0.46604669],
       [-1.26966293, -1.20258105,  1.32045289, -0.00765478,  0.09162024]])

In [130]:
np.round(array,decimals=3)

array([[-1.919, -0.296,  0.634,  0.118,  1.728],
       [-2.812,  0.406, -1.382, -1.326, -0.466],
       [-1.27 , -1.203,  1.32 , -0.008,  0.092]])

In [133]:
sports=np.array(['golf','cricket','fball','golf','fball','basketball'])

In [134]:
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')